.TH CLIENT 1 "Marzo 2025" "Versión 1.0" "Manual de client"
.SH NAME
client \- Cliente en C que consume la API en PHP
.SH SYNOPSIS
.B client
[OPCIONES]
.SH DESCRIPTION
Esta aplicación en C utiliza la librería cURL para realizar una solicitud HTTP a la API implementada en PHP.
.SH OPTIONS
Actualmente, no hay opciones configuradas.
.SH EXAMPLES
Para ejecutar el cliente, simplemente:
.nf
    ./client
.fi
.SH AUTHOR
Frangj66
.SH REPORTING BUGS
Envía tus reportes a <frangj66@gmail.com>.
